#!/usr/bin/env python3
import sys, os

SELF_PATH = os.path.dirname(os.path.realpath(__file__))
MOOSE_DIR = os.environ.get('MOOSE_DIR', os.path.abspath(os.path.join(SELF_PATH, 'moose')))

if not os.path.exists(os.path.join(MOOSE_DIR, 'python')) :
    MOOSE_DIR = os.path.abspath(os.path.join(SELF_PATH, '..', 'moose'))

if not os.path.exists(os.path.join(MOOSE_DIR, 'python')) :
    print("No moose installation was found. Set MOOSE_DIR or run `git submodule update --init moose`")

sys.path.append(os.path.join(MOOSE_DIR, 'python'))

os.environ["ENDF_FP_DIR"] = os.path.join(SELF_PATH, "data/fission_yield/")
os.environ["ALPHA_DIR"] = os.path.join(SELF_PATH, "data/alpha_decay/")

from TestHarness import TestHarness
app_name = 'magpie'
TestHarness.buildAndRun(sys.argv, app_name, MOOSE_DIR)
