#!/usr/bin/env python
import sys, os

MOOSE_DIR = os.environ.get('MOOSE_DIR', os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..', 'moose')))
sys.path.append(os.path.join(MOOSE_DIR, 'python'))

os.putenv("ENDF_FP_DIR", os.path.abspath(os.path.dirname(sys.argv[0])) + "/data/fission_yield/")
os.putenv("ALPHA_DIR", os.path.abspath(os.path.dirname(sys.argv[0])) + "/data/alpha_decay/")

from TestHarness import TestHarness
app_name = 'magpie'
TestHarness.buildAndRun(sys.argv, app_name, MOOSE_DIR)

